#+HTML_HEAD: <!-- -*- fill-column: 87 -*- -->
#+HTML_HEAD: <!-- org-toggle-inline-images -->

#+TITLE: Der Shlagbaumverk

#+INFOJS_OPT: view:overview toc:nil

#+NAME:css
#+BEGIN_HTML
<link rel="stylesheet" type="text/css" href="/css/css.css" />
#+END_HTML

Спецификация на разработку аппаратно-программного комплекса управления автоматизации
парковки

* Цель

  Создаем решение для оснащения платных парковок.

  Разрабатываемые компоненты:

  =Контроллер= - одноплатный микрокомпьютер на базе микроконтроллера архитектуры ARM
  Cortex-А7 или ARM Cortex-А9.

  Допускается:
  - использование готовых решений одноплатных микрокомпьютеров
  - варианты микропроцессоров с аналогичными характеристиками

  Возможно рассмотрение вариантов микропроцессоров отечественной разработки.

  =Плата расширения=, обеспечивающая функционал управления оборудованием автоматической
  парковки.

  =Сервисная программа контроллера= - прошивка для микроконтроллера, представляющая
  собой встраиваемую операционную систему на базе ядра Linux и развёрнутое на ней
  сервисное программное обеспечение.

  Функции:
  - Управление всеми вводами/выводами платы расширения
  - Настройку работы всего периферийного оборудования подключенного к
    плате расширения из браузера по IP-адресу контроллера.
  - Гибкая настройка алгоритмов и последовательности работы
    оборудования, подключенного к плате расширения
  - Подключение оборудования, используемого с платой расширения на лету (путем закачки
    и/или выбора динамических библиотек) без перезагрузки.
  - Выполнение функций абонентского устройства и взаимодействия с серверами IP связи/телефонии
  - Выполнить функцию абонентского устройства для IP связи с сервером парковки
  - Запрашивать и обрабатывать/хранить данные с IP камер
  - Осуществлять голосовое сопровождение пользователя на всех этапах работы с оборудованием
  - Управлять торговым/периферийным оборудованием подключенным к плате расширения
  - Вести логгирование работы системы.
  - Иметь защиту от несанкционированного подключения и выполнять шифрование трафика при общении с сервером.
  - Обладать максимальным возможным объемом автономности (независимости от серверного
    ПО)

  [TODO] - набор хотелок, которые покрывают вообще все. Надо хоть как-то привести к
  реализму. Иначе будет стоить как самолет и разрабатываться веками.

  разворачивается на самом контроллере, позволяет осуществлять настройку работы
  контроллера и тестирование периферийного оборудования через браузер по IP и порту
  контроллера.

  =Центральный сервер= - персональный компьютер, на котором развёрнута программа
  управления парковкой и хранится база данных со всеми настройками системы и
  пользователей, а также история событий.

  =Серверное ПО= - это программа управления парковкой, через которую осуществляется
  настройка всех основных модулей системы и управление парковочной системой. Серверное
  ПО имеет ядро (сервер приложений?, бэкенд?), базу данных под управлением выбранной
  СУБД, модульный интерфейс (фронтенд) и гибкую систему лицензирования и защиты
  программных средств.

  =Клиентский интерфейс= - интерфейс модуля сервера, доступный через браузер по IP
  адресу и заданному порту сервера, к которому получает доступ конечный пользователь
  системы.

  =Клиентская программа= - отдельно устанавливаемое на ПК (рабочую станцию) программное
  обеспечение, настраиваемое на взаимодействие с сервером, которое использует конечный
  пользователь системы.

  [TODO] - лучше пусть это будет броузер - дешевле выйдет в разработке и поддержке
  [Re] - ты уверен, что пробрасывать подключение торгового оборудования (сканер
  штрих-кодов и ККМ) в браузер - это просто? Ну и в перспективе нужна будет прога,
  которая сможет работать автономно с ограниченным функционалом.

* Описание функционирования

** Общий принцип работы

   Клиент на автомобиле вьезжает в зону действия =датчика присутствия=, нажимает на
   кнопку и получает =билет= со штрихкодом.

   =Датчик присутствия= - петля индуктивности, фотоэлемент, датчик магнитного поля.

   В будущем планируется адаптировать систему также под карты Mifare.

   В штрикоде зашифровано:
   - терминал вьезда
   - время вьезда
   - массогабаритные характеристики ТС клиента

   [TODO] - м.б. в обычный штрихкод последнее не влезет, надо уточнить
   [Re] 0 - легковой, 1 - средний, 2 - грузовая фура, в таком формате
   [TODO] - как именно зашифровано, нужно ли шифроваться от грамотного клиента, который
   может сопоставлять штрихкоды? Я аж даже заинтерсовался, пойти что-ли в Норд,
   посмотреть чем отличаются штрихкоды? :)
   [Re] Мы не в курсе механизма шифрования. На стойке и на сервере выставляется некий
   ключ. Как он шифрует этим ключём данные - не знаем.

   В =билете= также открытым текстом напечатано:
   - текущее время вьезда
   - номер терминала
   - номер сектора парковки / тарифной зоны
   - уникальный код билета (буквенно-цифровой)

   После того как пользователь возьмет билет, открывается шлакбаум.

   [TODO] - Есть ли датчик взятия билета? Добавить его в список периферии
   [Re] Это называется "презентер принтера", датчик в самом принтере и это штатные
   команды с принтера.

   Во время проезда машины под стрелой шлагбаума его закрытие невозможно - наличие
   автомобиля фиксируется фотоэлементом на линии стрелы и датчиком за ней). По факту
   проезда шлагбаум закрывается. После въезда начинается допустимое бесплатное время
   нахождения на парковке.

   Также имеется возможность попасть на парковку по бесконтактным картам доступа
   Em-Marine, которые заранее программируются и выдаются клиентам (система СКУД для
   постоянных клиентов и владельцев).

   Далее посетитель парковки должен произвести оплату парковочного времени. Это воможно
   сделать тремя осовными способами:
   - оплатить на автоматической кассе
   - оплатить на ручной кассе (ПК на котором опреатор в программе принимает оплату)
   - акцептировать билет у одного из арендаторов (сбросить время или перевести его на счёт арендатора)

   В любом случае информация с билета считывается с помощью сканера штрих кодов (для
   карт Mifare будет использоваться считыватель-программатор), либо на ПК вводом
   буквенно-цифрового кода с билета. При считывании посетителю сообщается сумма оплаты,
   которую он должен внести. По факту приёма оплаты печатается фискальный чек, он же
   выездной билет, а въездной билет аннулируется. Кроме оплаты билет может быть
   акцептирован (обнулён) арендатором с помощью специальной карты или на ПК (об этом
   подробнее в описании фнкционала акцептирования).

   Стоимость парковки может варьироваться в зависимости от времени пребывания на ней,
   тарифной сетки (разные тарифы в разное время суток и дни недели) и тарифных зон (на
   одной парковке может быть несколько секторов, в каждом из которых парковка стоит по
   разному, между ними стоят проездные стойки).

   После оплаты устанавливается допустимое время нахождения на парковке до выезда. Если
   посетитель находится больше времени, чем было установлено, ему необходимо снова
   оплачивать время.

   [TODO] - надо подробнее рассмотреть этот кейс.

   На выезде посетитель парковки при попадании автомобиля в зону действия датчика
   присутствия подносит свой билет к сканеру штрих кодов и, если допустимое время
   нахождения на парковке не истекло, ему позволяется покинуть парковку (в случае
   Mifare карт карта вставляется в приемник и он её заглатывает). Также имеется
   возможность покинуть парковку по бесконтактным Em-Marine картам доступа CКУД.

   [TODO] - Сразу видно вариант, как обмануть систему - заехать на парковку штатно, а
   когда надо выезжать - подьехать к вьезду на другой машине, взять билет и не
   вьезжать. Попросить можно кого-угодно из автомобилистов рядом. Потом по этому билету
   спокойно выезжаешь, пользуясь "бесплатным временем". Как планируется
   противодействовать такому сценарию?
   [Re] Это описано в алгоритме ниже. Если въезд не завершён до конца, то полученный
   билет аннулируется через время t. Но в целом бороться с этим надо в первую очередь
   административными методами. По факту такие ситуации крайне редко бывают. И у тех
   жмотов, у кого нет камер и парковщиков.

** Состояния контроллера при въезде

   Независимо от используемого комплекта периферийного оборудования контроллера при
   въезде может находится в следующих состояниях:

   [TODO] - для всех состояний необходимо описать условия входа и выхода в состояние,
   чтобы сгенерировать код диспетчера машины состояний.

*** Стойка в режиме ожидания

    Режим работы в котором датчик стойки не видит автомобиля и не идёт никакой другой
    процесс. В нём стойка реагирует на действия пользователя только сервисными
    сообщениями, выводя на дисплей либо сообщение о том, что нет автомобиля, либо
    сервисное сообщение о статусе карты/чека. Вся периферия неактивна.

*** Подъезд машины к стойке

    Процесс определения датчиком (петлёй индуктивности, фотоэлементом, датчиком
    магнитного поля) наличия машины у стойки, возможно массы и/или габаритов
    автотранспортного средства, а также контроля подъезда к стойке (например при
    проезде по рампе или через шлюз из двух шлагбаумов).

*** Стойка в активном режиме

    После срабатывания датчика присутствия стойка начинает диалог с посетителем, выводя
    на дисплей сообщения о необходимости совершения действий, ошибок и т.п. В этом
    режиме посетитель может нажать кнопку и получить от периферийного устройства
    въездной документ (чек или карту) или приложить к считывателю карту СКУД. На этом
    этапе осуществляется арбитраж в случае использования реверсивного проезда (один
    шлагбаум на две стойки с разных сторон) или использования двух стоек для левого и
    правого руля.

*** Инициация процедуры въезда

    После того, как посетителю разрешён въезд (из презентера устройства забран чек или
    карта, или успешно проверен статус карты СКУД) контроллер инициирует процесс
    открытия шлагбаума, замыкая соответсвующие реле и принимая сигналы с концевиков
    шлагбаума (или давая выставленный в секундах импульс, если концевиков нет).

*** Процедура проезда

    После открытия шлагбаума контроллер контролирует проезд машины под стрелой,
    принимая сообщения с датчика безопасности (фотоэлемент на линии стрелы) и датчика
    завершения проезда (петля индуктивности за стрелой, фотоэлмент, датчик МП). В эту
    же процедуру может входит контроль проезда по рампе или через шлюз, находящийся за
    стойкой.

*** Процедура завершения въезда

    Процесс закрытия шлагбаума после проезда машины, отправки итоговых данных о
    совершённом проезде на сервер и возвращения стойки в режим ожидания.

** Примеры алгоритмов
*** Алгоритм простого въезда по чеку

    Простейший алгоритм для парковки, работающей по чекам с стандартным комплектом
    датчиков и контроля проезда. В алгоритм введены светофор и счётчик мест
    (светодиодное табло).

    1. =Подъезд машины=
    1.1. Машина подъезжает к стойке, с сенсорного устройства у стойки (контроллер петли индуктивность, фотоэлемент и т.п.) на контроллер отправляется сигнал.
    1.2. Контроллер получает сигнал о том, что у стойки находится машина и из режима ожидания переховодит стойку в активный режим.
    1.3. Замыкается реле, отвечающее за красный сигнал на светофоре.
    1.4. На сервер отправляет инфосообщение "Машина у стойки въезда".
    2. =Активный режим (диалог спользователем)=
    2.1. Контроллер переводит периферийные устройства в режим обслуживания клиента:
         - включается подсветка кнопки печати билета;
         - на дисплей выдаётся информационное сообщение "Нажмите кнопку и получите билет".
    2.2. Клиент нажимает кнопку печати билета, сигнал с кнопки приходит на сенсорный вход контроллера.
    2.3. Контроллер получает сигнал на печать билета и отправляет на принтер команду "напечатать билет с необходимой информацией" (штрих-код, зашифрованный в соответствии с предустановленным кодом; текущее время; номер терминала въезда; номер тарифной зоны; предустановленную доп. информацию).
    2.4. Принтер печатает билет, его сенсоры контролируют состояние печати (возможно замятие, окончание бумаги и т.п.). Когда печать завершена билет находится в презентере.
    2.5. Контроллер блокирет перефирию, защищая систему от повторного получения въездного документа. На дисплей выводится сообщение "Забирите билет".
    2.6. Если билет не забран из презентера клиентом более t секунд - принтер сообщает об этом контроллеру, контроллер отбивает ошибку на сервер и анулирует билет.
    2.5. Еслли клиент забирает билет из презентера, принтер сообщает об этом контроллеру.
    2.6. Контроллер сообщает на сервер "Напечатан билет №".
    3. =Инициация проезда=
    3.1. Контроллер получает сигнал от принтера о том, что билет забран из презентера, что является действием, инициирующим процедуру проезда.
    3.2. Контроллер  замыкает реле, отвечающее за открытие шлагбаума  за стойкой (реле замкнуто либо до прихода на сенсорный ввод сигнала "открыт", либо по длине импульса из настроек контроллера)
    3.3. Контроллер сообщает серверу "Открытие шлагбаума стойки №"
    4. =Процедура проезда=
    4.1. Когда стрела шлагбаума открывается, в шлагбауме срабатывает концевик открытия - сигнал с него приходит на сенсор "открытие" контроллера
    4.2. Контроллер фиксирует факт того, что шлагбаум в открытом положении совершаются следующие действия:
         - замыкает реле, отвечающее за зелёный свет на светофоре;
         - размыкает реле, отвечающее за красный свет на светофоре;
         - сообщает серверу "Шлагбаум стойки № открыт"
    4.3. Когда машина пересекает линию фотоэлемента безопасности (стрелы шлагбаума) с ф/э приходит сигнал на сэнсор.
    4.4. Контроллер, имея сигнал с ф/э безопасности на сенсор, переходит в режим "стоп" - пока сенсор не освобождён стрела шлагбаума не должна закрыться.
    4.5. Машина проезжает шлагбаум,  с сенсорного устройства за его стрелой (контроллер петли индуктивности, фотоэлемент, датчик МП) на контроллер отправляется сигнал.
    4.6. Контроллер получает подтверждение завершения проезда и начинает соответсвующую процедуру.
    5. =Процедура завершения проезда=
    5.1. Получив подтверждение окончания проезда - нет сигнала на сенсор безопасности проезда и на сенсор петли за шлагбаумом - контроллер инициирует следующеи действия:
         - размыкает реле, отвечающее за зелёный свет на светофоре;
         - замыкает реле, отвечающее за красный свет на светофоре;
         - замыкает реле, отвечающее за закрытие шлагбаума за стойкой (реле замкнуто либо до прихода на сенсорный ввод сигнала "закрыт" с концевика, либо по длине импульса из настроек контроллера)
         - сообщает серверу "проезд по билету № успешно завершен", а также об изменении количества мест в секторе и данные по билету
         - отправляет на табло счётчика мест по RS-485 сообщение "-1 место"
    5.2. Получив сигнал с концевика закрытия на сенсор контроллер:
         - размыкает реле, отвечающее за красный свет на светофоре;
         - замыкает реле, отвечающее за зелёный свет на светофоре;
         - возвращает стойку в режим ожидания;
         - сообщает на сервер о закрытии шлагбаума.

*** Рампа

    Изменения касаются процедуры подъезда, всё начинается не с датчика присутствия у
    стойки, а с датчика в начале "шлюза" из двух шлагбаумов - одного в начале участка
    подъезда к стойке по рампе, второго - за стойкой. В данном решении присутсвуют три
    датчика присутвия - на начале шлюза, у стойки и за стрелой, а также фотоэлемент на
    линии стрелы.

    1.1. Машина начинает заезд на рампу, с сенсорного устройства в начале рампы (контроллер петли индуктивность, фотоэлемент и т.п.) на контроллер отправляется сигнал.
    1.2. Контроллер получает сигнал о том, что начат проезд рампы и переходит в режим ожидания освобождения сенсора.
    1.3. Машина начинает подъём по рампе,  сигнал с сенсорного устройства прекращается (оно остаётся позади машины).
    1.4. Контроллер фиксирует прекращение сигнала и блокирует рампу:
         - замыкает реле, отвечающее за закрытие шлагбаума №1, находящегося в начале рампы;
         - замыкает реле, отвечающее за красный свет на светофоре в начале рампы;
         - отправляет на сервер инфосообщение "Рампа занята".
    1.5. Машина подъезжает к стойке,  с сенсорного устройства у стойки (контроллер петли индуктивность, фотоэлемент и т.п.) на контроллер отправляется сигнал.
    1.6. Контроллер получает сигнал о том, что у стойки находится машина и инициирует процедуру инициации проезда.
    1.7. На сервер отправляет инфосообщение "Машина у стойки въезда".
    5.3. Контроллер открывает шлагбаум в начале рампы, зажигает зелёный свет на светофоре в начале рампы.
    5.4. На сервер отправляется сообщение "Рампа свободна".

*** Проезд по карте СКУД

    Карты СКУД формата Em-Marine могут использоваться параллельно с билетами или
    картами Mifare (основным въездным документом). Они вносятся в базу данных
    администратором парковки и имеют ряд опций и статусов о которых подробнее будет
    написано в описании модуля СКУД. Если пользователь вместо нажатия кнопки выдачи
    въездного документа прикладывает карту СКУД и она проходит успешно проверки - это
    действие является инициирующим проезд.

    2.1. Контроллер переводит периферийные устройства в режим обслуживания клиента:
         - включается подсветка кнопки печати билета;
         - на дисплей выдаётся информационное сообщение "Нажмите кнопку и получите билет ИЛИ ПРИЛОЖИТЕ КАРТУ".
    2.2. Клиент прикладывает карту к считывателю карт. Сигнал со считывателя Em-Marine приходит на интерфейс Wiegand 26.
    2.3. Контроллер получает сигнал о том, что приложена карат имеющая номер NNNNNNNN.
    2.4. Контроллер отправляет запрос на проверку статуса карты на сервер. Сервер обрабатывает запрос и возвращает контроллеру информацию о статусе карты:
         - "есть в БД" / "нет в БД" ;
         - "на парковке" / "вне парковки";
         - "заблокирована" / "активна";
         - "есть места для данной группы" / "нет мест для данной группы".
    2.5. Контроллер получает ответ от сервера и на его основании решает - пускать ли владельца карты на парковку или нет.
    2.6. Если сигнала связи с сервером нет, то контроллер проверяет свою БД и опрашивает другие контроллеры, которые видит в сети. Решение принимается на базе самой новой из доступных записей о статусе карты.
    2.8. Если въезд разрешён, контроллер инициирует процедуру проезда.
    2.9. На сервер отправляет инфосообщение "Приложена карта NNNNNNNN, въезд разрешен".

*** Фотофиксация въезда

    Опциональное действие, которое может совершаться параллельно с любым действием
    контроллера (выбирается в настройках контроллера). В процессе фотофиксации камера
    (или камеры), IP которой указан в настройках контролера, получает запрос на
    фотографирование, после чего возвращает контроллеру фото, которое сохраняетя им на
    SD носитель.

*** Звуковое сопровождение

    Опциональное действие, которое может совершаться параллельно с выводом сообщений на
    дисплей, дублируя их аудиозаписями, лежащими на SD носители. Данные аудиофайлы
    должны загружаться и сопоставляться с текстовыми сообщениями через интерфейс
    настройки контроллера.

** Состояния контроллера при выезде

   Выезд практически полностью аналогичен въезду. Его можно разделить на следующие
   процессы:

   [TODO] - если полностью аналогичен - зачем описывать?
   [Re] Сам сказал - описывай всё подробнее и дублирования не бойся. Основное
   различие - проверка статуса оплаты, а также возможность вклинить процедуру оплаты
   непосредственно в процесс.

*** Стойка в режиме ожидания

    Режим работы в котором датчик стойки не видит автомобиля и не идёт никакой другой
    процесс. В нём стойка реагирует на действия пользователя только сервисными
    сообщениями, выводя на дисплей либо сообщение о том, что нет автомобиля, либо
    сервисное сообщение о статусе карты/чека. Вся периферия неактивна.

*** Подъезд машины к стойке

    Процесс определения датчиком (петлёй индуктивности, фотоэлементом, датчиком
    магнитного поля) наличия машины у стойки, возможно массы и/или габаритов
    автотранспортного средства, а также контроля подъезда к стойке (например при
    проезде по рампе или через шлюз из двух шлагбаумов).

*** Стойка в активном режиме

    После срабатывания датчика присутствия стойка начинает диалог с посетителем, выводя
    на дисплей сообщения о необходимости совершения действий, ошибок и т.п. После
    прикладывания пользователем въездного документа, либо оплатного документа, либо
    карты СКУД, стойка соврешает проверку возможности выезда, статус оплаты и так
    далее. На этом этапе осуществляется арбитраж в случае использования реверсивного
    проезда (один шлагбаум на две стойки с разных сторон) или использования двух стоек
    для левого и правого руля. Также на этом этапе выезд может быть совмещён с оплатой
    и между процедурами 2 и 3 выполняется процедура оплаты, как на автоматическом
    кассовом терминале.

*** Инициация процедуры выезда

    После того, как посетителю разрешён въезд (из презентера устройства забран чек или
    карта, или успешно проверен статус карты СКУД) контроллер инициирует процесс
    открытия шлагбаума, замыкая соответсвующие реле и принимая сигналы с концевиков
    шлагбаума (или давая выставленный в секундах импульс, если концевиков нет).

*** Процедура проезда

    После открытия шлагбаума контроллер контролирует проезд машины под стрелой,
    принимая сообщения с датчика безопасности (фотоэлемент на линии стрелы) и датчика
    завершения проезда (петля индуктивности за стрелой, фотоэлмент, датчик МП). В эту
    же процедуру может входит контроль проезда по рампе или через шлюз, находящийся за
    стойкой.

*** Процедура завершения въезда

    Процесс закрытия шлагбаума после проезда машины, отправки итоговых данных о
    совершённом проезде на сервер и возвращения стойки в режим ожидания.

* Примеры алгоритмов
** Алгоритм простого выезда по чеку

   Простейший алгоритм для парковки, работающей по чекам с стандартным комплектом
   датчиков и контроля проезда. В алгоритм введены светофор и счётчик мест
   (светодиодное табло).

   1. =Подъезд машины=
   1.1. Машина подъезжает к стойке, с сенсорного устройства у стойки (контроллер петли индуктивность, фотоэлемент и т.п.) на контроллер отправляется сигнал.
   1.2. Контроллер получает сигнал о том, что у стойки находится машина и из режима ожидания переховодит стойку в активный режим.
   1.3. Замыкается реле, отвечающее за красный сигнал на светофоре.
   1.4. На сервер отправляет инфосообщение "Машина у стойки выезда".
   2. =Активный режим (диалог с пользователем)=
   2.1. Контроллер переводит периферийные устройства в режим обслуживания клиента:
   - активируется широкополосный сканер штрих-кода;
   - на дисплей выдаётся информационное сообщение "Поднесите билет".
   2.2. Клиент подносит билет штрих-кодом к сканеру, данные по RS232 или USB передаются на контроллер.
   2.3. Контроллер  расшифровывает с помощью ключа шифрования (аналогичный стоит на въезде и кассах) штрих-код, получая из него информацию об оставшемся бесплатном времени (со времени въезда или времени оплаты). Он решает, исходя из заложенных в себя тарифов и параметров времени, разрешёен въезд или требуется оплата времени. см. "ПРОВЕРКА РАЗРЕШЕНИЯ ВЫЕЗДА"
   2.4. Исходя из результатов проверки контроллер выводит на дислпей сообщение "Выезд разрешён" или "Выезд запрещён, оплатите $$$ руб".
   2.5. Если выезд запрещён, контроллер блокирет перефирию, защищая систему от повторного прикладывания чека.
   2.6. Контроллер сообщает на сервер "Выезд по билету №".
   3. =Инициация проезда=
   3.1. Контроллер получает положительный ответ от внутренних и внешних механизмов проверки оплаты билета и инициирует процедуру проезда.
   3.2. Контроллер  замыкает реле, отвечающее за открытие шлагбаума  за стойкой (реле замкнуто либо до прихода на сенсорный ввод сигнала "открыт", либо по длине импульса из настроек контроллера)
   3.3. Контроллер сообщает серверу "Открытие шлагбаума стойки №"
   4. =Процедура проезда=
   4.1. Когда стрела шлагбаума открывается, в шлагбауме срабатывает концевик открытия - сигнал с него приходит на сенсор "открытие" контроллера
   4.2. Контроллер фиксирует факт того, что шлагбаум в открытом положении совершаются следующие действия:
        - замыкает реле, отвечающее за зелёный свет на светофоре;
        - размыкает реле, отвечающее за красный свет на светофоре;
        - сообщает серверу "Шлагбаум стойки № открыт"
   4.3. Когда машина пересекает линию фотоэлемента безопасности (стрелы шлагбаума) с ф/э приходит сигнал на сэнсор.
   4.4. Контроллер, имея сигнал с ф/э безопасности на сенсор, переходит в режим "стоп" - пока сенсор не освобождён стрела шлагбаума не должна закрыться.
   4.5. Машина проезжает шлагбаум,  с сенсорного устройства за его стрелой (контроллер петли индуктивности, фотоэлемент, датчик МП) на контроллер отправляется сигнал.
   4.6. Контроллер получает подтверждение завершения проезда и начинает соответсвующую процедуру.
   5. =Процедура завершения проезда=
   5.1. Получив подтверждение окончания проезда - нет сигнала на сенсор безопасности проезда и на сенсор петли за шлагбаумом - контроллер инициирует следующеи действия:
        - размыкает реле, отвечающее за зелёный свет на светофоре;
        - замыкает реле, отвечающее за красный свет на светофоре;
        - замыкает реле, отвечающее за закрытие шлагбаума за стойкой (реле замкнуто либо до прихода на сенсорный ввод сигнала "закрыт" с концевика, либо по длине импульса из настроек контроллера)
        - сообщает серверу "выезд по билету № успешно завершен", а также об изменении количества мест в секторе и данные по билету
        - отправляет на табло счётчика мест по RS-485 сообщение "-1 место"
   5.2. Получив сигнал с концевика закрытия на сенсор контроллер:
        - размыкает реле, отвечающее за красный свет на светофоре;
        - замыкает реле, отвечающее за зелёный свет на светофоре;
        - возвращает стойку в режим ожидания;
        - сообщает на сервер о закрытии шлагбаума.

** Проезд по карте СКУД

   Карты СКУД формата Em-Marine могут использоваться параллельно с билетами или картами
   Mifare (основным въездным документом). Они вносятся в базу данных администратором
   парковки и имеют ряд опций и статусов о которых подробнее будет написано в описании
   модуля СКУД. Если пользователь вместо нажатия кнопки выдачи въездного документа
   прикладывает карту СКУД и она проходит успешно проверки - это действие является
   инициирующим проезд.

   2.1. Контроллер переводит периферийные устройства в режим обслуживания клиента:
   - включается подсветка кнопки печати билета;
   - на дисплей выдаётся информационное сообщение "Нажмите кнопку и получите билет ИЛИ ПРИЛОЖИТЕ КАРТУ".
   2.2. Клиент прикладывает карту к считывателю карт. Сигнал со считывателя Em-Marine приходит на интерфейс Wiegand 26.
   2.3. Контроллер получает сигнал о том, что приложена карат имеющая номер NNNNNNNN.
   2.4. Контроллер отправляет запрос на проверку статуса карты на сервер. Сервер обрабатывает запрос и возвращает контроллеру информацию о статусе карты:
        - "есть в БД" / "нет в БД" ;
        - "на парковке" / "вне парковки";
        - "заблокирована" / "активна";
        - "есть места для данной группы" / "нет мест для данной группы".
   2.5. Контроллер получает ответ от сервера и на его основании решает - пускать ли владельца карты на парковку или нет.
   2.6. Если сигнала связи с сервером нет, то контроллер проверяет свою БД и опрашивает другие контроллеры, которые видит в сети. Решение принимается на базе самой новой из доступных записей о статусе карты.
   2.8. Если въезд разрешён, контроллер инициирует процедуру проезда.
   2.9. На сервер отправляет инфосообщение "Приложена карта NNNNNNNN, выезд разрешен".

** Фотофиксация въезда

   Опциональное действие, которое может совершаться параллельно с любым действием
   контроллера (выбирается в настрйоках контроллера). В процессе фотофиксации камера
   (или камеры), IP которой указан в настройках контролера, получает запрос на
   фотографирование, после чего возвращает контроллеру фото, которое сохраняетя им на
   SD носитель.

** Звуковое сопровождение

   Опциональное действие, которое может соврешаться параллельно с
   выводом сообщений на дисплей, дублируя их аудиозаписями, лежащими
   на SD носители. Данные аудиофайлы должны загружаться и
   сопоставляться с текстовыми сообщениями через интерфейс настройки
   контроллера.

** Работа с автоматической кассой

   АЛГОРИТМЫ СКОПИРОВАНЫ ИЗ ПАСПОРТА КАССЫ, В ПРОЦЕССЕ ДОРАБОТКИ

*** Процедура оплаты

    Это последовательность действий посетителя и оператора парковки
    при проведении оплаты через автоматическую кассу.

    1. Посетитель находится у кассы.
    1.1. Подносит неоплаченный въездной билет или просроченный выездной чек к сканеру штрих-кода.
    1.2. Если посетитель потерял въездной билет или выездной чек, то он должен нажать кнопку "Оплата за утерю билета" (точная формулировка может отличаться).
    2. На дисплее выводится информация о необходимых операциях.
    2.1. В случае, если бесплатное или ранее оплаченное время ещё не истекло, на дисплей будет выведена информация об оставшемся времени нахождения на парковке.
    2.2. Если посетитель пробыл на парковке больше установленного бесплатного времени и не провёл оплату на другой кассе или производит оплату за утерю билета, система рассчитает сумму, требуемую к оплате, исходя из установленных для стойки тарифов, выведет на дисплей информацию о необходимости и размере платежа и активирует платёжное оборудование.
    3. Посетитель оплачивает услуги АПС наличными через купюроприемник (банкноты номиналом 50, 100, 500, 1000 и 5000 руб.; мод. К, БК, КМ, БКМ), монетоприёмник (монеты номиналом 1, 2, 5 и 10 руб., мод. М, КМ, БМ, БКМ) или банковской карточкой (мод. Б, БК, БМ, БКМ).
    3.1. Если оплата производится купюрами или монетами, и при внесении платежа была совершена ошибка, возможно вернуть деньги нажав кнопку "Возврат денег".
    3.2. Если оплата производится монетами, и при внесении платежа монету заклинило в монетоприёмнике, необходимо нажать на кнопку "Сброс монеты" под прорезью для монет.
    3.3. Если оплата производится с помощью банковской карты, то для активации POS-терминала необходимо нажать кнопку "Оплата картой".
    4. После оплаты касса выдаёт выездной чек и, в случае, если посетитель оплатил наличными и сумма вносимых средств превысила требуемую, сдачу. При этом на мониторе отображается оставшееся время, в соответствии с установленными тарифами, в течение которого посетитель должен покинуть парковку.

*** Процедура инкассации

    2. Запросить "Х-отчет" и забрать чек. п. 3 и п. 4 только для модификаций с купюрами (К, БК, КМ, БКМ)
    3. Изъять банкнотную наличность.
    3.1. Снять бокс купюроприёмника
    3.2. Изъять купюры из бокса или взять пустой бокс купюроприёмника
    3.3. Установить пустой бокс купюроприемника на место.
    4. Восполнить банкнотную наличность для сдачи.
    4.1. Снять кассеты диспенсера с купюрами сдачи и кассету "Отказ".
    4.2. Заполнить кассеты купюрами или взять предварительно заполненные сдачей новые кассеты. Изъять неликвидные купюры из кассеты "Отказ".
    4.3. Установить кассеты на место.
    5. Провести инкассацию и закрыть смену.
    5.1. Нажать кнопку "Инкассация" и забрать чек с данными об инкассации. п. 6 и п. 7 только для модификаций с монетами (М, КМ, БМ, БКМ)
    6. Изъять полученные монеты из специального металлического ящика.
    7. После нажатия "Инкассации" выполнить перезагрузку сдачи в хопперы.
    7.1. Хопперы автоматически поочерёдно осуществят сброс всех не выданных в качестве сдачи монет в окно выдачи сдачи или в предварительно размещённую под желобами для монет ёмкость. 7.2. Загрузите в хопперы сдачу в соответствии с установленным по умолчанию количеством сдачи. п. 8 только для модификаций с банковскими картами (Б, БК, БМ, БКМ)
    8. После нажатия "Инкассации" POS-терминал обменивается данными с банком, после чего в чек инкассации включается отчёт об эквайринговых операциях.
    9. Если на дисплее отображается надпись "Заблокировано", необходимо нажать кнопку "Разблокировка", после чего будет напечатан тестовый чек и выведена надпись "Поднесите штрих-код или карту".
    10. Закрыть дверь кассы.

*** Процедура закрытия смены

    2. Запросить "Z-отчет", закрыть фискальную смену и забрать чек. Сверить суммы прибыли с чеками инкассаций и фактической прибылью.
    3. Новая смена открывается автоматически при следующей оплате.
    4. Если на дисплее отображается надпись "Заблокировано", необходимо нажать кнопку "Разблокировка", после чего будет напечатан тестовый чек и выведена надпись "Поднесите штрих-код или карту".
    5. Закрыть кассу.

*** Проверка разрешения выезда

    Разрешение для посетителя на пребывание на парковке в течение определенного
    промежутка времени задается арендатором. При этом клиентская программа арендатора
    шлет информацию на центральный сервер, а центральный сервер сохраняет информацию и
    транслирует ее контроллеру. Контроллер сохраняет полученную информацию в
    памяти. При выезде автомобиля контроллер проверяет, истек срок пребывания на
    парковке или нет, и разрешает или запрещает выезд. Время выезда передается на
    центральный сервер.

*** Работа контроллера при обрыве связи с сервером

    Работа контроллера в случае обрыва связи с сервером
    осуществляется следующим образом. Билет считывается сканером
    штрих кодов. Время и код билета сохраняются в памяти
    контроллера. Решение об открытии ворот принимается охранником (на
    билете напечатано время въезда). При восстановлении связи архив
    информации о билетах передается на центральный сервер.

* Особенности секторальности и тарификации

  Необходимо реализовать гибкую систему тарифов, при этом постаравшись максимально сохранить автномность системы в случае падения связи с сервером.
  Основне единые настройки бесплатного времени:
  - бесплатное время после въезда (мин)
  - бесплатное время на выезд после оплаты (мин)
  Имеются следующие основыне тарифные характеристики:
  - стоимость 1го..2го..23го..24го.. часа после истечения бесплатного времени
  - коэффициент стоймости в зависимости от времени суток (с 20:00 до 22:00 k=2, с 9:00 до 18:00 k=0,5)
  - коэффицикнт стоймости в зависимости от дня недели (пн, вт, ср, чт, пт k2=1, сб,вс k2=2)
  Эти характеристики должны быть индивидуальны для разных секторов парквоки. Т.е.,
  например, в секторе открытого паркинга одни тарифы, а в секторе закрытого -
  другие. Между секторами стоит проездная стойка со сканером штрих кодов (для Mifare
  парковки это сделать проще в автономном режиме). При поднесении она переносит на
  сервере и всех соседних стойках билет в другой сектор. При этом если машина отстояла
  t1 времени в одном секторе, а потом поехала в другой, то данные по оплате
  суммируется, а бесплатное время во втором секторе не считается.

* Протоколы обмена данными

  Контроллеры и рабочие станции соединяются с центральным сервером по локальной сети,
  используя стек протоколов TCP/IP.

  Некоторые периферийные компоненты системы могут связываться с контроллерами или
  непосредственно с сервером и рабочими станциями по интерфейсу RS-485

* Периферийные устройства контроллера и протоколы связи

  Периферийное оборудование
  |    | Тип устройства                                               | Предлагаемая модель        | Интерфейс подключения   |
  |  1 | Термопринтер                                                 | Custom VKP80II             | RS-232 / USB            |
  |  2 | Фискальный регистратор                                       | Искра ПРИМ-21К 03          | RS-232 / USB            |
  |  3 | Сканер штрихкодов широкополосный                             | Honywell IS3480 QuantumE   | RS-232 / USB            |
  |  4 | Сканер штрихкода / QR-кода                                   | не выбрана                 | RS-232 / USB            |
  |  5 | Диспенсер карт Mifare+                                       | не выбрана                 | RS-232 / USB            |
  |  6 | Картоприёмник Mifare+                                        | не выбрана                 | RS-232 / USB            |
  |  7 | Считыватель карт Mifare+Matrix II MF-I                       | Wiegand 26                 |                         |
  |  8 | Считыватель карт Em-MarineIron Logic Matrix V / Matrix II EH | Wiegand 26                 |                         |
  |  9 | Дисплей монохромный символьный 16*4                          | Winstar / Long             | 6800 / SPI              |
  | 10 | Дисплей цветной графический TFT-LCD                          | Winstar / Long             | RGB / MCU               |
  | 11 | Купюроприемник                                               | CashCode SM (MSM)          | ID003 / CCNET           |
  |    |                                                              | ICT L77F                   | RS-232                  |
  | 12 | Монетоприемник                                               | ICT UCA2                   | RS-232                  |
  | 13 | Диспенсер купюр                                              | Puloon LCDM-1000/2000/4000 | RS-232                  |
  |    |                                                              | ICT ND 300 KM              | RS-232                  |
  | 14 | Хоппер                                                       | ICT Leonid Mini Hopper     | ccTalk / Hopper         |
  | 15 | Ресайклер монет                                              | не выбрана                 | RS-232                  |
  | 16 | POS банк-терминал                                            | не выбрана                 | RS-232 / USB / Ethernet |
  | 17 | Табло счётчика мест / инфотабло                              | не выбрана                 | RS-485                  |
  | 18 | Ультразвуковой датчик наличия машины                         | не выбрана                 | RS-485                  |
  | 19 | Магнитный датчик наличия машины                              | не выбрана                 | RS-485                  |
* Выводы на аудио оборудование
  |    | Тип устройства    | Предлагаемая модель | Интерфейс подключения |
  | 20 | Вывод на динамик  | Jack 3,5 мм TS      |                       |
  | 21 | Вывод на микрофон | Jack 3,5 мм TS      |                       |
* Выводы на сухой контакт реле
  |    | Тип устройства                      | Предлагаемая модель | Интерфейс подключения |
  | 22 | Шлагбаум вверх                      | R1                  |                       |
  | 23 | Шлагбаум вниз                       | R2                  |                       |
  | 24 | Шлагбаум стоп                       | R3                  |                       |
  | 25 | Светофор сигнал 1                   | R4                  |                       |
  | 26 | Светофор сигнал 2                   | R5                  |                       |
  | 27 | Светофор сигнал 3                   | R6                  |                       |
  | 28 | Арбитраж вывод                      | R7                  |                       |
  | 29 | Доп. реле управления смежными устр. | R8                  |                       |
  | 30 | Доп. реле управления смежными устр. | R9                  |                       |
  | 31 | Доп. реле управления смежными устр. | R10                 |                       |
* Выводы на сенсоры и кнопки
  |    | Тип устройства                  | Предлагаемая модель | Интерфейс подключения |
  | 32 | Датчик присутсвия автомобиля А  | S1                  |                       |
  | 33 | Датчик присутсвия автомобиля Б  | S2                  |                       |
  | 34 | Датчик завершения проезда рампы | S3                  |                       |
  | 35 | Арбитраж ввод                   | S4                  |                       |
  | 36 | Концевки открытия шлагбаума     | S5                  |                       |
  | 37 | Концевик закрытия шлагбаума     | S6                  |                       |
  | 38 | Фотоэлемент безопасности        | S7                  |                       |
  | 39 | Датчик грузового транспорта     | S8                  |                       |
  | 40 | Универсальная кнопка 1          | S9                  |                       |
  | 41 | Универсальная кнопка 2          | S10                 |                       |
  | 42 | Универсальная кнопка 3          | S11                 |                       |
  | 43 | Универсальная кнопка 4          | S12                 |                       |
  | 44 | Универсальная кнопка 5          | S13                 |                       |
  | 45 | Универсальная кнопка 6          | S14                 |                       |
  | 46 | Общий                           | S15                 |                       |

* Серверная часть

  Серверную часть необходимо полностью переписать в соответствии со
  следующими критериями:

  - Необходимо отойти от связки php+appche, сервер должен иметь
    автономное ядро (бэкэнд, сервер приложений) которое возможно будет
    развернуть на платформах ОС семейств Windows или Linux. Выбор
    оптимальных средств (языка программирования) с помощью которых
    будет реализована данная задача на данный момент является
    приоритетной задачей.

  - В качестве сервера БД предлагается использовать бесплатные системы
    MySQL с базами InnoDB или PostgreSQL (выбор необходимо
    аргументировать).

  - Все требуемые администратору системы и конечному пользователю
    интерфейсы и средства должны быть реализованы в кроссплатформенном
    браузерном варианте. Т.е. система должна быть реализована по
    принципу "одного окна" (или точнее "всё на одной вкладке
    браузера"). В дальнейшем возможно создание клиентских приложений на
    замену браузерной реализации, но данная задача не является
    приоритетной.

  - Сервер должен иметь модульную структуру как по функционалу, так и
    по доступным конечным пользователям интерфейсам управления и
    администрирования (фронтэнду). Модули должны подключаться к серверу
    в процессе изначальной установки, либо легко подключаться
    после. Необходимо предусмотреть возможность инсталляции модулей как
    с носителя, так и из сетевого репозитория.

  - Ядро сервера и модули должны иметь встроенные средства
    защиты. Предполагается использование аппаратного ключа HASP или
    RuToken (возможно аналогов) для ядра и отдельных программных ключей
    лицензирования для подключения отдельных модулей.

  - При создании сервера необходимо разработать APIи техническую
    документацию для возможности дальнейшей интеграции нашего ПО с
    системами СКУД, 1С и т.д.

  - Необходима возможность объединения серверов в кластеры,
    т.е. несколько локальных серверов на отдельных парковках должны
    иметь возможность обмениваться информацией с центральным сервером в
    центре управления. Центральный сервер же должен иметь приоритет над
    локальными, имея возможность управлять СКД во всём кластере,
    тарифами и т.д.

* Основной функционал сервера:

  В базовом варианте сервер должен иметь собственно ядро, БД и два
  основных модуля (интерфейса) - администратора системы и парковщика.

  Администратор системы должен иметь следующие возможности:

  - Получать информацию обо всех стойках и терминалах, находящихся в
    локальной сети по факту настройки стоек на работу с данным сервером.

  - Изменение IP-адресов, ключей шифрования, номеров стоек, управления
    секторами, временем, информацией, выводимой на дисплей стоек и
    печатаемой на чеках, подключения и удалённого программного
    отключения периферийного оборудования на них (торговое
    оборудование, светофоры, табло), гибкой настройки логики работы
    сенсоров (фотоэлементов, магнитных петель).

  - Получение информации агрегируемую сервером со стоек - события
    въездов, выездов, оплаты, ошибки и т.п., которая должна писать в лог
    и быть доступна для выгрузке по дате в отчёт в формате *.xls.

  - Доступ к средствам тестирования работоспособности стоек (аналог
    текущего ParkingTest).

  - Управление пользователями системы, создание логинов и паролей,
    распределение прав доступа к интерфейсам из-под учётных записей и
    групп пользователей системы (в том числе и для самого себя).

  Оператор парковки должен иметь следующие возможности:

  - Открытие и закрытие шлагбаумов, подключённых к стойкам, находящимся
    в локальной сети.

  - Управление количеством свободных мест на парковке.

  - Мониторинг информации, приходящей со стоек (лога) в режиме
    реального времени.

* Дополнительные модули сервера

  Дополнительные модули должны подключаться к системе по запросу клиента в тех или иных
  сочетаниях. При этом, каждый из этих установленных модулей подключается
  администратором системы конкретному пользователю (группе пользователей).

** Модуль =платной парковки=

   Добавляет возможность работы с оплатой парковочного времени и управляет тарифами на
   парковке. В системы добавляется интерфейс администратор тарифов, с помощью которого
   можно изменять почасовую стоимость пребывания на парковке, бесплатное время
   пребывания на парковке, время бесплатного выезда с парковки после оплаты услуг и
   т.д.

** Модуль =СКУД=

   Добавляет возможность работы с бесконтактными картами доступа в безусловном режиме
   разрешения / запрета въезда. В систему добавляется интерфейс администратора СКУД,
   который позволяет заводить в систему карты доступа по их индивидуальному номеру,
   вводить информацию о владельцах карт (ФИО, гос. номер транспортного средства и
   т.п.), распределять карты по различным группам доступа. Группы доступа могут иметь
   различные права по времени возможного въезда/выезда с парковки, по посещению тех или
   иных секторов парковки, а также иметь численное ограничение количества въездов
   (т.е. карт выдано в группе 10, но данной группе на парковке принадлежит только 5
   мест и одновременно на парковке / в секторе парковки может находиться только 5
   машин). Карты доступа могут временно блокироваться, переноситься в архивные и
   окончательно удаляться администратором. Если установлены другие модули, работающие с
   б/к картами, администратор может изменять тип карт с одного на другой (абонемент,
   дебетовая). У оператора парковки при подключённом модуле СКУД в логе добавляются
   сообщения о въездах и выездах по картам. Также добавляется интерфейс аудитора СКУД,
   который позволяет пользователю с данными правами получить доступ к информации о
   картах доступа, но не даёт возможности её изменять.

** Модуль для =работы с абонементами=

   Добавляет возможность работы с бесконтактными картами в режиме оплаты услуг парковки
   владельцем карты на заданный срок - т.е. оплата на фиксированную сумму производится
   один раз в установленный срок. В систему добавляется интерфейс администратора
   абонементных карт,позволяющий заводить в систему абонементные карты по их
   индивидуальному номеру, вводить информацию о владельцах карт (ФИО, гос. номер
   транспортного средства, номер договора на предоставление услуг и т.п.), распределять
   карты по различным группам доступа и тарифными группам. Группы доступа используются
   те же, что и в модуле СКУД. Абонементные карты могут временно блокироваться,
   переноситься в архивные и окончательно удаляться администратором. Если установлены
   другие модули, работающие с б/к картами, администратор может изменять тип карт с
   одного на другой (СКУД, дебетовая).В интерфейс администратора тарифов добавляется
   возможность работы с тарифными группами, сроками и стоимостью оплаты для
   абонементов.У оператора парковки, при подключённом модуле работы с абонементами, в
   логе добавляются сообщения о въездах и выездах по картам и сроке действия
   карт. Также добавляется интерфейс аудитора абонементных карт, который позволяет
   пользователю с данными правами получить доступ к информации об абонементных картах
   исроках оплаты клиентом услуг, но не даёт возможности её изменять.

** Модуль для =работы по дебетовым картам=

   Добавляет возможность работы с бесконтактными картами в режиме оплаты услуг парковки
   владельцем карты по специальному тарифу - т.е. он кладёт деньги на карту через
   кассу, сумма фиксируется в платёжной системе парковки и далееденьги списываются с
   него исходя из времени пребывания на парковке при выездах, но по особым тарифам. В
   систему добавляется интерфейс администратора дебетовых карт,позволяющий заводить в
   систему дебетовые карты по их индивидуальному номеру, вводить информацию о
   владельцах карт (ФИО, гос. номер транспортного средства, номер договора на
   предоставление услуг и т.п.), распределять карты по различным группам доступа и
   тарифными группам. Группы доступа используются те же, что и в модуле СКУД. Дебетовые
   карты могут временно блокироваться, переноситься в архивные и окончательно удаляться
   администратором. Если установлены другие модули, работающие с б/к картами,
   администратор может изменять тип карт с одного на другой (СКУД, абонементная).В
   интерфейс администратора тарифов добавляется возможность работы с тарифными группами
   и стоимостью времени пребывания на парковке для дебетовых карт.У оператора парковки,
   при подключённом модуле работы с дебетовыми картами, в логе добавляются сообщения о
   въездах и выездах по картам и списанных со счёта средствах. Также добавляется
   интерфейс аудитора дебетовых карт, который позволяет пользователю с данными правами
   получить доступ к информации о дебетовых картах, состоянии счёта клиента и тарифном
   плане, но не даёт возможности ничего изменять.

** Модуль =акцептирования=

   Добавляет в систему возможность обнуления требующего оплаты билета со штриховым
   кодом через интерфейсную оболочку. В систему добавляется интерфейс акцептирования
   билета в котором пользователь может ввести в специальное поле номер билета (или
   считать номер сканером штрих-кода) и произвести либо безусловное акцептирование -
   сделать билет бесплатным для выезда навсегда изменив информацию о нём на сервере и
   выездных стойках, либо акцептирование на выезде- у клиента будет возможность
   покинуть парковку в течении бесплатного времени после акцептирования, либо
   акцептирование по тарифу - данному билету присваивается специальный тариф
   (используется список тарифов дебетового режима) и стоимость пребывания на парковке
   пересчитывается исходя из него. При акцептировании пользователь вводит комментарий,
   в котором пишется причина акцептирования. Вся информация о проведённых
   акцептированиях билетов (пользователь, номер билета, время акцептирования, сумма
   акцептирования) пишется в лог и доступна для ознакомления в интерфейсе аудитора
   акцептирования.

** Модуль =арендаторов=

   Добавляет в систему возможность обнуления требующего оплаты билета со штриховым
   кодом на кассах, стойках информации или через интерфейсную оболочку с помощью карты
   арендатора с последующим списанием обнулённой суммы на счёт владельца карты. В
   систему добавляется интерфейс администрирования арендаторов, в котором можно
   создавать пользователей - "арендаторов" и привязывать их бесконтактным картам и
   основным пользователям системы. Каждому арендатору выдаётся своя бесконтактная
   карта, для которой в системе администратором установлен режим акцептирования (режимы
   перечислены в описании модуля акцептирования, для дебетового режима устанавливается
   тариф). С помощью этой карты арендатор может акцептировать билет клиента, приложив
   сначала билет, а затем карту к стойке информации, кассе или введя номер билета на
   ПК, а затем приложив карту к считывателю на ПК. После этого клиент покидает парковку
   в соответствии с правилами акцептирования, а акцептированная сумма переводится на
   "овердрафтовый счёт" данного арендатора в системе. Все данные по этому счёту
   отображаются в интерфейсе счета арендаторов. Через этот интерфейс можно либо списать
   сумму, которую должен арендатор, либо распечатать фискальный чек через ККМ,
   подключённый к ПК, либо выгрузить форму счёта на оплату в банке.

** Модуль =кассира=

   Добавляет в систему возможность оплаты услуг парковки через ручную кассу на базе ПК
   к которому подключён ККМ и, опционально, денежный ящик и сканер штриховых кодов. В
   систему добавляются интерфейсы кассир и кассир - парковщик. В интерфейсе кассира
   пользователь может провести процедуру оплаты билета - вбить его номер (или считать
   номер сканером штрих-кода), выбрать тариф оплаты, принять сумму к оплает и
   распечатать выездной фискальный чек с суммой, рассчитанной системой исходя из
   времени и тарифа. При этом приём денег и выдача сдачи осуществляется непосредственно
   человеком. Кассир-парковщик имеет интерфейс оплаты совмещённый с интерфейсом
   обычного оператора парковки в котором есть возможность открытия и закрытия
   шлагбаума, доступ к логу и т.п.

** Модуль =бухгалтера=

   Добавляет в систему возможность получения финансовых отчётов по парковке и кассовым
   аппаратам (нарастающий итог, оборот по кассам и т.п.), а также делает возможным
   автоматическое снятие Z-отчётов, печать копий Z-отчётов, изъятие установленной суммы
   из автоматической кассы и т.д.

** Модуль =фотофиксации=

   Добавляет в систему фотографирования камерами по событию. В интерфейсе
   администратора системы добавляется функция привязки камеры к конкретной стойке и
   список событий, производимых со стойкой, по которым камера должна производить
   фотографирование. Во все логи, в том числе и у оператора парковки, к сообщениям о
   данных событиях прикрепляются фотографии. Также добавляются интерфейсы машины на
   парковке и аудиторфотофиксации в которых можно посмотреть фотографии всех машин,
   которые приехали на парковку и находятся на ней и, соответственно, приехали и уехали
   с парковки в установленный промежуток времени.

** Модуль =распознания номеров=

   Интеграция с SIP сервером VoIP связи Asterisk

** Модуль =дуплексной IP связи=

* Контроллер (требования)

   Новый контроллер парковочной системы должен быть разработан в соответствии со
   следующими критериями:

** Гибкость системы

   Плата и программное обеспечение должны быть выполнены так, чтобы была возможность
   масштабирования системы и при этом сохранения обратной совместимости программного
   обеспечения. Например, в определённый момент возникнет необходимость увеличить
   количество реле или COM-портов на плате, будет осуществлена доработка связанная с
   переразводкой, но при этом на новых контроллерах должно штатно работать и старое ПО,
   а на старых контроллерах работать новое ПО.

** Web-интерфейс для настройки контроллера

   Микроконтроллер должен иметь собственный Web-сервер для возможности доступа к его
   настройкам через локальную сеть по IP адресу и наличия функции перепрошивки и
   обновления программного обеспечения контроллера без физического доступа к нему.

** Обработка аудио

   Наличие модуля обработки аудио, аппаратного или возможности установки программного
   эккалайзера

** Работа с дисплеями

   монохромный 2,4строки и полноцветнный габаритами
